kind: pipeline
name: default

steps:

- name: build
  image: node:9.8.0
  commands:
  - sh ./.drone/build.sh

- name: publish
  image: plugins/docker
  settings:
    repo: nishanthkp/nodeapp
    auto_tag: true
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
