version: 2.1
orbs:
  slack: circleci/slack@volatile
executors:
  node:
    docker:
      - image: 'circleci/node:9.8.0'
    shell: /bin/bash
    working_directory: ~/app
    environment:
      TEST_REPORTS: ~/reports
      SLACK_WEBHOOK: https://hooks.slack.com/services/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
jobs:
  build:
    executor: node
    steps:
      - checkout
      - restore_cache:
          keys:
            # Find a cache corresponding to this specific package-lock.json checksum
            # when this file is changed, this key will fail
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            # Find the most recently generated cache used from any branch
            - v1-npm-deps-
      - run:
          name: Install Node.js dependencies with Npm
          command: npm install
      - save_cache:
          paths:
            - ./node_modules
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
      - persist_to_workspace:
          root: ~/app
          paths:
            - .
  test:
    executor: node
    steps:
      - attach_workspace:
          at: ~/app
      - run:
          name: Test
          command: npm test
      - run:
          name: Save test results
          command: |
            set -xu
            npm install nyc mocha-junit-reporter
            mkdir ${TEST_REPORTS}
            ./node_modules/.bin/nyc ./node_modules/.bin/mocha spec.js --recursive --timeout=10000 --exit --reporter mocha-junit-reporter --reporter-options mochaFile=${TEST_REPORTS}/mocha/test-results.xml
          environment:
            MOCHA_FILE: ${TEST_REPORTS}/test-results.xml
          when: always
      - store_test_results:
          path: ${TEST_REPORTS}
      - store_artifacts:
          path: ${TEST_REPORTS}
workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          pre-steps:
            - slack/notify:
                message: Build of ${CIRCLE_BRANCH} started.
                color: '#42e2f4'
                webhook: ${SLACK_WEBHOOK}
      - test:
          post-steps:
            - slack/status:
                webhook: https://hooks.slack.com/services/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
          requires:
            - build